export const gameMock = [
    { bust: 2, hash: 'hash_1' },
    { bust: 2, hash: 'hash_2' },
    { bust: 2, hash: 'hash_3' },
    { bust: 2, hash: 'hash_4' },
    { bust: 2, hash: 'hash_5' },
    { bust: 1.22, hash: 'hash_6' },
    { bust: 5.7, hash: 'hash_7' },
    { bust: 80, hash: 'hash_8' },
    { bust: 32.2, hash: 'hash_9' },
    { bust: 14.1, hash: 'hash_10' },
    { bust: 15.0, hash: 'hash_11' },
    { bust: 3.2, hash: 'hash_12' },
    { bust: 4.4, hash: 'hash_13' },
    { bust: 5.2, hash: 'hash_14' },
    { bust: 5.1, hash: 'hash_15' },
    { bust: 4.22, hash: 'hash_16' },
    { bust: 1.07, hash: 'hash_17' },
    { bust: 1.08, hash: 'hash_18' },
    { bust: 5, hash: 'hash_19' },
    { bust: 3, hash: 'hash_20' },
    { bust: 2, hash: 'hash_20' }
]
