export const playersMock = [
    { bust: 100, hash: 'hash_1' },
    { bust: 5, hash: 'hash_2' },
    { bust: 5, hash: 'hash_3' },
    { bust: 5, hash: 'hash_4' },
    { bust: 5, hash: 'hash_5' },
    { bust: 5, hash: 'hash_6' },
    { bust: 5, hash: 'hash_7' },
    { bust: 5, hash: 'hash_8' },
    { bust: 5, hash: 'hash_9' },
    { bust: 5, hash: 'hash_10' },
    { bust: 5, hash: 'hash_11' },
    { bust: 5, hash: 'hash_12' },
    { bust: 5, hash: 'hash_13' },
    { bust: 5, hash: 'hash_14' },
    { bust: 5, hash: 'hash_15' },
    { bust: 5, hash: 'hash_16' },
    { bust: 5, hash: 'hash_17' },
    { bust: 5, hash: 'hash_18' },
    { bust: 5, hash: 'hash_19' },
    { bust: 5, hash: 'hash_20' }
]